services:
  - type: web
    name: disktro-backend
    env: docker
    plan: starter
    region: frankfurt
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        sync: false # tu ajoutes la vraie valeur sur Render dashboard

databases:
  - name: disktro-mysql
    plan: starter
    region: frankfurt
    ipAllowList: [] # autorise toutes les connexions depuis ton service
    databaseName: disktro_db
